### ISSUE TITLE
tell me how can I create boot image and what file I shoud replace it with 

### ISSUE THREAD

**Issue by 8-momo-8** [daoudeddy/Kernel-Actions#1]
I am runing 19.1 lineageos i tried to replace the kernal file with boot.img-kernel and i flashed it but i can not boot to the system after reboot I enter the fastboot 
[Archive.zip](https://github.com/daoudeddy/Kernel-Actions/files/9385565/Archive.zip)
I used the boot.img should I use dbto.img please help should i try 18.1 os  to create the new boot img  I used Android Image Kitchen
thanks

**Comment by daoudeddy** [comment]
Please check this [guide](https://gist.github.com/FreddieOliveira/efe850df7ff3951cb62d74bd770dce27), it should work on any Android version.

**Comment by 8-momo-8** [comment]
I don't know how to flash the kernel from this file "Image.gz-dtb" my phone is Poco x3 nfc  is there is instructions for that how to compile the kernel and flash it

**Comment by daoudeddy** [comment]
use Anykernel flashable zip
